"""initial database

Revision ID: ae5d0010233c
Revises: 
Create Date: 2026-03-05 23:57:27.838470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5d0010233c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontaj', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start1', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('stop1', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('start2', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('stop2', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('observatii', sa.String(length=200), nullable=True))
        batch_op.drop_column('stop')
        batch_op.drop_column('start')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.DateTime(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('created')

    with op.batch_alter_table('pontaj', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('stop', sa.VARCHAR(length=10), nullable=True))
        batch_op.drop_column('observatii')
        batch_op.drop_column('stop2')
        batch_op.drop_column('start2')
        batch_op.drop_column('stop1')
        batch_op.drop_column('start1')

    # ### end Alembic commands ###
